ls:
  apps/*/src:
    .dir:
      kebab-case | regex:_internals | regex:__tests__ | regex:__stories__ |
      regex:__mocks__
    .test.ts: kebab-case
    .queries.ts: kebab-case
    .d.ts: kebab-case
    .ts: kebab-case
    .server.ts: kebab-case
    .client.ts: kebab-case
    .svelte: PascalCase
    .md: PascalCase

  apps/*/src/routes:
    .dir:
      kebab-case | regex:_internals | regex:__tests__ | regex:__stories__ |
      regex:__mocks__ | regex:\[[a-z][a-zA-Z0-9-]+(?:=[a-z][a-zA-Z0-9_]+)?\] |
      regex:\([a-z][a-z0-9-]+\)
    .js:
      regex:[+]page(?:[.]server)? | regex:[+]layout(?:[.]server)? |
      regex:[+]server
    .ts:
      regex:[+]page(?:[.]server)? | regex:[+]layout(?:[.]server)? |
      regex:[+]server
    .svelte: regex:[+]page | regex:[+]layout | regex:[+]error
    .md: PascalCase

  packages/*/*/lib:
    .dir:
      kebab-case | regex:_internals | regex:__tests__ | regex:__stories__ |
      regex:__mocks__

ignore:
  - .git
  - .github
  - .husky
  - .vscode
  - .eslintrc.js
  - .svelte-kit
  - node_modules
  - dist
